[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib', "dependencies"]
test = 'test'
cache_path  = 'cache_forge'
optimizer=true
via_ir=true

[dependencies]
forge-std = "1.9.7"

remappings = [
    "forge-std-1.9.7/=dependencies/forge-std-1.9.7/"
]
